### PR TITLE
Electron Logging

### PR DESCRIPTION
**Pull request by oren-icx**

### CODE REVIEW

**Comment by perry-icx** [comment]
So this sends the JS console log to a file?

**Comment by oren-icx** [comment]
No, it adds it to the pm2/npm logs

**Comment by perry-icx** [comment]
Yeah that's what I meant to say (the pm2 logs are saved to a file somewhere)

Next time someone notices the "Web Audio API is not supported" - we should trace this log and maybe finally understand what's the problem there.

**Comment by oren-icx** [comment]
Oh, didn't know.
Where is the pm2 log file? I only saw the python daemons logs.

**Comment by perry-icx** [comment]
It's default location is ~/.pm2/logs 

Also installed pm2-logrotate so the logs there will rotate when the file gets too large

**Comment by oren-icx** [comment]
Also, another thing that I just thought of is the Electron version, which we keep static at 1.6.10 (Electron contains Chromium versions inside).

I see that latest electron is 1.8.4 and that the upstream MagicMirror reverted to 1.4.15.

**Comment by perry-icx** [comment]
Interesting, it seems that upstream MagicMirror does not contain any interesting updates, except maybe this revert - it says old Electron versions work better on Raspberry Pi than new ones... I wonder if that would be the same (or opposite) on the NUCs. One simple thing to check might be the lag in the CSS animations on NUC - if that happens in a later/earlier Electron+Chromium version. In any case, I think that lagness can be fixed on the software size, since it doesn't make a lot of since that simple CSS animations lag and the complicated 3D WebGL animation doesn't.


On another note, I noticed this merge is to master - but the relevant branch is "smx" - but I guess this is confusing and unnecessary - so I will merge now smx into master as well.

**Comment by perry-icx** [comment]
And another thing, does this require any change to the file ~/smx.sh ? That file is currently not under the repository.

I want to update the chinese smart mirrors and make sure im doing it right

**Comment by oren-icx** [comment]
Yeah, forgot about the smx/master branches.

No update to the smx.sh.

**Comment by oren-icx** [comment]
electron 1.8.4 didn't do any change to the subtitles jumping.
Also didn't find any drivers to install :/

**Pull request merged**
